print("Hell")
# JUSTIN NABUNTURAN ALL OVER DA WORLD # JUSTIN NABUNTURAN ALL OVER DA WORLD 
# JUSTIN NABUNTURAN ALL OVER DA WORLD 
# JUSTIN NABUNTURAN ALL OVER DA WORLD 

# JUSTIN NABUNTURAN ALL OVER DA WORLD 
# JUSTIN NABUNTURAN ALL OVER DA WORLD 
# JUSTIN NABUNTURAN ALL OVER DA WORLD 
